// web-dashboard/src/views/Inbox.vue
<script setup lang="ts">
import { onMounted } from 'vue';
import { useContentStore } from '../stores/content';
import ContentCard from '../components/content/ContentCard.vue';

const contentStore = useContentStore();

onMounted(async () => {
  contentStore.updateFilters({ status: 'inbox' });
  await contentStore.loadPlatforms();
});

const handleDelete = async (id: number) => {
  try {
    await contentStore.deleteItem(id);
  } catch (error) {
    console.error('Delete failed:', error);
  }
};

const handleSwipe = async (action: { content_id: number; action: 'keep' | 'discard' }) => {
  try {
    await contentStore.performSwipe(action);
  } catch (error) {
    console.error('Swipe failed:', error);
  }
};
</script>

<template>
  <div class="inbox">
    <div class="page-header">
      <h1>Inbox</h1>
      <p>Content waiting to be processed</p>
    </div>

    <div class="filters">
      <label class="filter-label">
        Platform:
        <select
          v-model="contentStore.filters.platform"
          @change="contentStore.loadContent(1)"
          class="filter-select"
        >
          <option value="">All Platforms</option>
          <option
            v-for="platform in contentStore.platforms"
            :key="platform.platform"
            :value="platform.platform"
          >
            {{ platform.platform }} ({{ platform.count }})
          </option>
        </select>
      </label>
    </div>

    <div class="content-grid">
      <ContentCard
        v-for="item in contentStore.items"
        :key="item.id"
        :content="item"
        @delete="handleDelete"
        @swipe="handleSwipe"
      />
    </div>

    <div v-if="contentStore.isLoading" class="loading">
      Loading...
    </div>

    <div v-if="!contentStore.items.length && !contentStore.isLoading" class="empty">
      <p>Your inbox is empty! 🎉</p>
    </div>
  </div>
</template>

<style scoped>
.inbox {
  padding: 24px;
  max-width: 1400px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 24px;
}

.page-header h1 {
  font-size: 28px;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 8px;
}

.page-header p {
  color: var(--text-secondary);
  font-size: 16px;
}

.filters {
  margin-bottom: 24px;
}

.filter-label {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 14px;
  color: var(--text-secondary);
}

.filter-select {
  padding: 8px 12px;
  border: 1px solid var(--border-color);
  border-radius: 6px;
  background: var(--bg-secondary);
  color: var(--text-primary);
  font-size: 14px;
  cursor: pointer;
}

.content-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 24px;
}

.loading,
.empty {
  text-align: center;
  padding: 48px;
  color: var(--text-secondary);
}
</style>

// web-dashboard/src/pages/Inbox.tsx
import { useEffect, useState } from 'react';
import { useContentStore } from '../stores/useContentStore';
import ContentCard from '../components/content/ContentCard';
import styles from './Inbox.module.css';

export default function Inbox() {
  const contentStore = useContentStore();
  const [selectedPlatform, setSelectedPlatform] = useState('');

  useEffect(() => {
    contentStore.updateFilters({ status: 'inbox' });
    void contentStore.loadPlatforms();
  }, []);

  const handleSwipe = async (action: { content_id: number; action: 'keep' | 'discard' }) => {
    await contentStore.performSwipe(action);
  };

  const handleDelete = async (id: number) => {
    await contentStore.deleteItem(id);
  };

  const handlePlatformChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const platform = e.target.value || undefined;
    setSelectedPlatform(e.target.value);
    contentStore.updateFilters({ platform });
  };

  return (
    <section className={styles.page} data-testid="inbox-page">
      <header className={styles.hero}>
        <p className={styles.kicker}>Swipe Queue</p>
        <h1>One card at a time, no backlog guilt.</h1>
      </header>

      <div className={styles.filterRow}>
        <label htmlFor="platform-filter">Source</label>
        <select
          id="platform-filter"
          value={selectedPlatform}
          onChange={handlePlatformChange}
          className={styles.select}
        >
          <option value="">All platforms</option>
          {contentStore.platforms.map((platform) => (
            <option key={platform.platform} value={platform.platform}>
              {platform.platform} ({platform.count})
            </option>
          ))}
        </select>
      </div>

      {contentStore.isLoading ? <p className={styles.message}>Refreshing queue…</p> : null}

      {!contentStore.items.length && !contentStore.isLoading ? (
        <p className={styles.message}>Inbox clear. You&apos;re fully caught up.</p>
      ) : null}

      <div className={styles.grid}>
        {contentStore.items.map((item) => (
          <ContentCard
            key={item.id}
            content={item}
            onDelete={handleDelete}
            onSwipe={handleSwipe}
          />
        ))}
      </div>
    </section>
  );
}
