// web-dashboard/src/App.tsx
import { Outlet, useLocation } from 'react-router-dom';
import Header from './components/layout/Header';
import ErrorBoundary from './components/ErrorBoundary';

function App() {
  const location = useLocation();

  const showHeader = location.pathname !== '/login' && location.pathname !== '/oauth-callback';

  const handleError = (error: Error) => {
    console.error('Global error:', error);
    // Could send to error tracking service here
  };

  return (
    <ErrorBoundary onError={handleError}>
      <div id="app">
        {showHeader && <Header />}
        <main className="main-content">
          <Outlet />
        </main>
      </div>
    </ErrorBoundary>
  );
}

export default App;

// web-dashboard/src/App.vue
<script setup lang="ts">
import { computed } from 'vue';
import { RouterView, useRoute } from 'vue-router';
import Header from './components/layout/Header.vue';
import ErrorBoundary from './components/ErrorBoundary.vue';

const route = useRoute();

const showHeader = computed(() => route.name !== 'Login' && route.name !== 'OAuthCallback');

const handleError = (error: Error) => {
  console.error('Global error:', error);
  // Could send to error tracking service here
};
</script>

<template>
  <ErrorBoundary :onError="handleError">
    <div id="app">
      <Header v-if="showHeader" />
      <main class="main-content">
        <RouterView />
      </main>
    </div>
  </ErrorBoundary>
</template>

<style scoped>
#app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.main-content {
  flex: 1;
}
</style>
